BoxLayout:
    orientation: 'horizontal'

    BoxLayout:
        orientation: 'vertical'

        GridLayout:
            cols: 2

            Button:
                text: "Btn1"
                background_color: 0, 1, 1, 1
                font_size: 20

            Button:
                text: "Something"
                background_color: 0, 1, 1, 1
                font_size: 20

            Button:
                text: "Btn2"
                background_color: 0, 1, 1, 1
                font_size: 20

            Button:
                text: "Something"
                background_color: 0, 1, 1, 1
                font_size: 20
            
            Button:
                text: "Btn2"
                background_color: 0, 1, 1, 1
                font_size: 20

            Button:
                text: "Something"
                background_color: 0, 1, 1, 1
                font_size: 20

            Button:
                text: "Btn2"
                background_color: 0, 1, 1, 1
                font_size: 20

            Button:
                text: "Something"
                background_color: 0, 1, 1, 1
                font_size: 20

            Button:
                text: "Btn2"
                background_color: 0, 1, 1, 1
                font_size: 20

            Button:
                text: "Something"
                background_color: 0, 1, 1, 1
                font_size: 20

            
        BoxLayout:
            orientation: 'horizontal'

            FloatLayout:
                MDIconButton:
                    icon: "/home/anubhav/gui_ws/icons/arrow_l.png"
                    icon_size: "100sp"
                    pos_hint: {"center_x": 0.1, "center_y": 0.25}

                MDIconButton:
                    icon: "/home/anubhav/gui_ws/icons/arrow_r.png"
                    icon_size: "100sp"
                    pos_hint: {"center_x": 0.4, "center_y": 0.25}

                MDIconButton:
                    icon: "/home/anubhav/gui_ws/icons/arrow_u.png"
                    icon_size: "100sp"
                    pos_hint: {"center_x": 0.25, "center_y": 0.4}

                MDIconButton:
                    icon: "/home/anubhav/gui_ws/icons/arrow_d.png"
                    icon_size: "100sp"
                    pos_hint: {"center_x": 0.25, "center_y": 0.1}   

            FloatLayout:
                MDIconButton:
                    icon: "/home/anubhav/gui_ws/icons/arrow_l.png"
                    icon_size: "100sp"
                    pos_hint: {"center_x": 0.1, "center_y": 0.25}

                MDIconButton:
                    icon: "/home/anubhav/gui_ws/icons/arrow_r.png"
                    icon_size: "100sp"
                    pos_hint: {"center_x": 0.4, "center_y": 0.25}

                MDIconButton:
                    icon: "/home/anubhav/gui_ws/icons/arrow_u.png"
                    icon_size: "100sp"
                    pos_hint: {"center_x": 0.25, "center_y": 0.4}

                MDIconButton:
                    icon: "/home/anubhav/gui_ws/icons/arrow_d.png"
                    icon_size: "100sp"
                    pos_hint: {"center_x": 0.25, "center_y": 0.1} 

    FloatLayout:


    
        
          
